### ISSUE TITLE
FE: 마이페이지 데이터 리패치 및 모집카드 컴포넌트 태그 잘림 이슈 수정

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#109]
#Description
현재 마이페이지에서 데이터 수정시 바로 리패치 못하는 이슈가 있습니다. 또한 모집카드 모바일 뷰에서 태그가 길어지면 잘리는 이슈가 있습니다.
해당 2가지 이슈를 해결합니다.

# To-do
- [x] 마이페이지 데이터 패치
- [x] 태그 잘림 이슈 해결

# ETC
- [x] 카드 모바일 뷰 css 수정
- [x] 기타 리팩토링
