### ISSUE TITLE
FE: 모집카드, 자랑카드 디자인 변경

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#122]
#Description
모집카드와 자랑 카드 모바일 css 를 수정합니다.
타 css 를 수정합니다.

# To-do
- [x] 모집카드 css 수정
- [x] 자랑카드 css 수정
- [x] 기타 css 수정

# ETC
