### ISSUE TITLE
FE: 랜딩페이지 서비스 설명 파트 구현, 이미지 및 로고 제작, 무한 롤링 배너 구현

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#126]
#Description
svg 파일의 속성을 변경하여 다크모드와 라이트 모드의 색상을 조정합니다. 랜딩페이지의 메인 이미지를 적용합니다.

# To-do
- [x] 로고를 적용합니다.
- [x] 상단 메인 이미지를 적용합니다.
- [x] 무한 롤링배너를 구현합니다.
- [x] 서비스를 설명하는 페이지를 기획 및 구현합니다.
- [x] svg 파일에 다크모드/라이트모드 색상 설정을 합니다.

# ETC
