### ISSUE TITLE
FE: 카드 컴포넌트 및 마이페이지 레이아웃 재조정

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#133]
#Description
카드 컴포넌트와 마이페이지의 레이아웃을 조정합니다.

# To-do
- [x] 자랑카드 width 깨짐 이슈 해결
- [x] 모집카드 마이페이지 내 레이아웃 상이함 이슈 해결
- [x] 알람카드 레이아웃 조정
- [x] 마이페이지 내 레이아웃 조정

# ETC
