### ISSUE TITLE
FE: UXUI수정

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#139]
#Description
UXUI를 수정합니다.
# To-do
- [x] deleteToast를 삭제합니다.
- [x] 알람 보더를 수정합니다.
- [x] 페이지가 전환될 때 알람창을 숨깁니다.
- [x] 마이페이지 내에서 필터링 된 게시물이 없을 때 문구를 추가합니다.
# ETC
