### ISSUE TITLE
FE:  UX/UI 수정

### ISSUE THREAD

**Issue by taejinii** [Side-Effect-Team/side-effect-frontend#140]
#Description
 부족한 UI/UX을 개선합니다.
# To-do
- [x] 프로젝트 게시판 모바일뷰 필터 패딩 추가
- [x] 랜딩페이지 배스트프로젝트 섹션 height 수정
- [x] SelectBox 컴포넌트 box-shadow 수정

# ETC
