### ISSUE TITLE
FE: 랜딩페이지 및 목록페이지의 게시글 컴포넌트 구현

### ISSUE THREAD

**Issue by ad105geppetto** [Side-Effect-Team/side-effect-frontend#2]
#Description
랜딩페이지와 목록페이지(모집/자랑)에서 사용되는 컴포넌트를 구현합니다.

# To-do
- [x] 랜딩페이지 프로그래밍 언어 카드 구현
- [x] 모집 목록 페이지의 게시글 컴포넌트 구현
- [x] 자랑 목록 페이지의 게시글 컴포넌트 구현

# ETC

**Comment by ad105geppetto** [comment]
작업 완료
