### ISSUE TITLE
FE: 지원자 현황 및 관리를 위한 모달 컴포넌트 구현

### ISSUE THREAD

**Issue by taejinii** [Side-Effect-Team/side-effect-frontend#38]
#Description
리덕스 툴킷을 사용한 사이드 프로젝트 지원자 현황 및 관리를 위한 모달 구현 
# To-do
- [x] 모달 레이아웃 구현
- [x] 포지션별 지원자 현황 필터 구현
- [x] 지원자 수락,거절 기능 구현

# ETC
