### ISSUE TITLE
FE:Toast 컴포넌트 예외상태 추가 

### ISSUE THREAD

**Issue by taejinii** [Side-Effect-Team/side-effect-frontend#58]
#Description
성공여부,에러발생여부 와 별개로 예외발생여부를 알려주는 타입 추가 
# To-do
- [x] 예외발생 타입 토스트 추가
- [x] 예외발생 토스트 디자인 
- [x] 토스트컴포넌트 디자인 개선

# ETC
