### ISSUE TITLE
FE: 프로젝트 자랑게시판  UI/UX 개선 리팩토링

### ISSUE THREAD

**Issue by taejinii** [Side-Effect-Team/side-effect-frontend#79]
#Description

![화면 기록 2023-05-21 오전 1 34 56](https://github.com/Side-Effect-Team/side-effect-frontend/assets/96623949/53eca39e-ece3-4ef1-986a-eef95bf0499c)

 프로젝트 자랑게시판 필터시 카드컴포넌트 들이 리렌더링되면서 화면이 위아래로 움직이는듯한 효과를 주고있습니다. 이를 개선합니다.

팀원 모집게시판과 자랑게시판 두곳에서 쓰기위한 옵저버 컴포넌트를 만듭니다.

# To-do
- [x] 옵저버 컴포넌트
- [x] 필터시 리랜더링으로 인한 안좋은 UX 개선
- [x] 데이터를 로딩중일때 를 나타내는 UI 구현
- [x] 프로젝트페이지 코드를 조금더 선언적으로 리팩토링

# ETC
