### ISSUE TITLE
FE: 카드 컴포넌트 UI 개선

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#80]
#Description
카드 컴포넌트 ui를 변경합니다.
태그의 개수가 많아지면 제한된 div 높이로 인해 일부분이 보이지 않게됩니다. 또한 태그가 차지하는 높이에 따라 ui의 통일성이 사라집니다.
이 문제를 해결하기 위해 태그를 한줄로 할당시키고 너비안에 들어가지않는 태그들은 +n 개로 표현하려 합니다.
# To-do
- [ ] 태그 위치 변경
- [ ] 태그 너비에 따른 포함될 태그, 비포함 될 태그 구하는 함수 구현
- [ ] 기타 ui 개선

# ETC
