### ISSUE TITLE
FE: 카드 컴포넌트 ui 변경 

### ISSUE THREAD

**Issue by ju-ju2** [Side-Effect-Team/side-effect-frontend#96]
#Description
기존의 공통 카드컴포넌트에서 모집글, 자랑글 각각의 게시물에 적용되도록 분리합니다.
# To-do
- [x] hover 시 애니메이션 적용
- [x] 모집, 자랑 게시글 컴포넌트 분리
- [ ] 자랑글 스켈레톤 구현

# ETC
